---
on:
  push:
  workflow_dispatch:

jobs:
  fmt:
    runs-on: 'self-hosted'
    steps:
      - uses: 'actions/checkout@v4'
      - uses: 'actions/setup-go@v5'
        with:
          go-version-file: 'go.mod'
      - run: |
          make tidy no-dirty
  test:
    runs-on: 'self-hosted'
    steps:
      - uses: 'actions/checkout@v4'
      - uses: 'actions/setup-go@v5'
        with:
          go-version-file: 'go.mod'
      - run: |
          make check tidy no-dirty
